# Site settings
baseURL = 'https://jakobschumacher.github.io/'
languageCode = 'de-de'
title = 'Jakob Schumacher'
theme = 'hugo-split-theme'

# Enable robots.txt generation
enableRobotsTXT = true

# Copyright
copyright = "&copy;2025 Jakob Schumacher"

[params]
  # Metadata for search engines and social sharing
  author = "Jakob Schumacher"
  description = "Webseite von Jakob Schumacher - Infektionsepidemiologe, Mediziner, Data scientist und Dozent"
  shareImage = "images/jakob.jpg"

  # Whether you purchased the license from the author.
  licensed = false

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/jakob.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true

  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Projekte"

      [[params.links.list1.link]]
        text = "Infektionsschutzkompendium"
        url = "https://jakobschumacher.github.io/infektionsschutzkompendium/"
        new_tab = true

      [[params.links.list1.link]]
        text = "Merkblätter für Infektionskrankheiten"
        url = "https://jakobschumacher.github.io/merkblaetter/"
        new_tab = true

      [[params.links.list1.link]]
        text = "Alle Projekte"
        url = "/epiprojects/"
        new_tab = false

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Kontakt"

      [[params.links.list2.link]]
        text = "GitHub"
        url = "https://github.com/jakobschumacher"
        new_tab = true

# Markup settings
[markup]
  [markup.highlight]
    style = 'monokai'
    lineNos = false
